apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: development
data:
  bob: "This is the content of the file bober."
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  init-script.sh: |
    #!/bin/sh
    touch /etc/bober
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
  namespace: development
type: Opaque
data:
  DATABASE_PASSWORD: cGFzc3dvcmQ=  # base64-encoded value of "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: LOG_LEVEL
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-app-secret
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: log-volume
              mountPath: /var/log/nginx
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: config-volume
          configMap:
            name: demo-app-config
        - name: log-volume
          emptyDir: {}

