apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: development
data:
  bob: "This is the content of the file bober."
  ENVIRONMENT: "development"
  LOG_LEVEL: "debug"
  init-script.sh: |
    #!/bin/sh
    touch /etc/bober
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      initContainers:
        - name: init-script
          image: busybox
          volumeMounts:
            - name: config-volume
              mountPath: /config
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: LOG_LEVEL
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: config-volume
          configMap:
            name: demo-app-config
