apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: 21.1.1  # You can specify the desired Keycloak version
      sourceRef:
        kind: HelmRepository
        name: keycloak-repo
        namespace: flux-system
  values:
    keycloak:
      username: admin  # Default admin username
      password: 
        secretKeyRef:
          name: keycloak-secret  # Replace with your secret name
          key: admin-password   # Key in the secret to store the password
    ingress:
      enabled: true
      ingressClassName: "nginx"  # Change this based on your ingress controller
      hosts:
        - keycloak.mycluster218  # Replace with your domain name
      path: /
      tls:
        - hosts:
            - keycloak.mycluster218  # Same as above
          secretName: keycloak-tls-secret  # Optional TLS secret
    service:
      type: ClusterIP  # Change this if you need external access (e.g., LoadBalancer)
      port: 8080       # The port exposed by the service
      targetPort: 8080 # The port Keycloak listens on
    replicaCount: 2    # Number of replicas to deploy (for high availability)
    keycloakDeployment:
      podDisruptionBudget:
        minAvailable: 1  # At least one pod should be available during disruptions
    persistence:
      enabled: true
      storageClass: "standard"  # Set your storage class or leave as default
      accessMode: ReadWriteOnce
      size: 10Gi  # Size of the Persistent Volume
    externalAccess:
      enabled: true
      host: keycloak.mycluster218  # Use the same domain as Ingress
      tls:
        enabled: true
        secretName: keycloak-tls-secret
