apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://www.keycloak.org/docs/latest/helm-chart
